### ISSUE TITLE
Tests for invalid links to assets in markdown files

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/sec.club#101]
We should test our markdown files for invalid links to other routes, and invalid links to image assets.

**Comment by carpenterd777** [comment]
Do we want to render anything special in the case that an invalid image is referenced in the markdown file or do we just want it to behave like a broken `<img />` tag would?

**Comment by dyc3** [comment]
The current behavior is that if an image is referenced but it doesn't exist, the entire article fails to render. I think we should keep that behavior, and extend it so that happens with invalid links as well. It'll make it easier to catch mistakes before they get deployed
