### ISSUE TITLE
UX: header and footer should not be visible when on slide deck pages

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/sec.club#147]
The header and footer take up unnecessary screen space when looking at slides, so they should be hidden. However, the header should still be accessible in some form for navigation.

**Comment by carpenterd777** [comment]
Which design would be better: dropping a `SlideDeck` in any view would cause the header and footer to be hidden, or designing a new view specifically for slides that hides them by default? Or do you think a third option I didn't list would be better?

**Comment by dyc3** [comment]
There should be a new view specifically for presenting slide decks that hides them.
