### ISSUE TITLE
Add jsben.ch to resources

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/sec.club#169]
URL: https://jsben.ch/
This is a tool for: Javascript
Description: Benchmark code performance directly in the browser

**Comment by carpenterd777** [comment]
What does this tool do? Maybe when we add this to the resources we should add a small description because I'm not sure how to use it just by looking at it

**Comment by dyc3** [comment]
I agree, we should definitely start adding descriptions. I've added a description to the issue body above.
