### ISSUE TITLE
Add article discussing a little bit about some topics from GBM 2

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/sec.club#173]
During GBM 2, we went over topics such as:

-  a basic git workflow 
- a little bit about the github cli 
- what wsl is useful for
-  showing off git integration with VScode
-  reading the code from other developers on a project
- repl.it as a testing playground for foreign code
- debugging by reading documentation

**Comment by dyc3** [comment]
We've already completed a couple of these, and I think most of these are big enough to split into their own issues.

**Comment by dyc3** [comment]
Closing because stale
