### ISSUE TITLE
As a user, I would like to interact with menu items within the header in order to navigate through the website

### ISSUE THREAD

**Issue by bsalgado98** [StevensSEC/sec.club#3]
Follow the design specs that @grinchpal outlined in her wireframe. This ticket pertains strictly to the MenuItem.jsx component which should be able to take in a "text" prop that decides what to render on the button as well as a "route" prop that decides where to take the user upon clicking.

Two menu item types:
- Regular button
- Drop down menu

**Comment by carpenterd777** [comment]
Now that we've implemented a Drawer component, is this ticket still relevant?
