### ISSUE TITLE
As a public relations chair, I want to be able to update the website with new flyers

### ISSUE THREAD

**Issue by bsalgado98** [StevensSEC/sec.club#6]
This is a long term, nice-to-have, feature that would basically involve creating an external way for @swiessler to upload flyers and event details without having to spin up the dev environment. We want to make it as simple as possible. Some ideas are:
### Python hooks:
- Python script to hook into Google Drive and check for file changes
- Anytime an image file is uploaded, it will detect this and also check for a .txt file of the same name
- It will download both files and automatically generate a template code snippet that just adds a new Flyer.jsx component using the image file and the parsed out data from the .txt file
### Electron app:
- Electron (JavaScript for desktop apps) app that provides a simple UI for inputting a flyer and event details
- See last point in "Python hooks" section

**Comment by dyc3** [comment]
After discussing in an EBM on 2/4, we are going to treat flyers like we treat articles. New flyers should be put in the repo and committed, and then they can be referenced in react.
