### ISSUE TITLE
Add link to join mailing list

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/sec.club#64]

**Comment by carpenterd777** [comment]
Can members add themselves or is it up to us to add them to the mailing list?

**Comment by dyc3** [comment]
https://lists.stevens.edu/mailman/listinfo/sec

**Comment by carpenterd777** [comment]
I found that too I just didn't know if it was okay for members to use it

**Comment by dyc3** [comment]
CS club has a similar link on their website
