### ISSUE TITLE
As a user, I would like to view an about me page in order to learn more about SEC

### ISSUE THREAD

**Issue by bsalgado98** [StevensSEC/sec.club#7]
Create a AboutUs.jsx component that contains general information about our club (our objective as a club, what we do normally, Semester Long Project, etc...). Once React Router is implemented, ensure that this feature behaves nicely with Router.

**Comment by elenirotsides** [comment]
Is the about us component a menu item? Or is this its own entity? @bsalgado98 
Also, what is a React Router? I will do my own research on it (don't worry) but why do we need it?

**Comment by bsalgado98** [comment]
### Good questions!!
1. The AboutUs.jsx component will have a corresponding MenuItem.jsx component. Whoever develops the Header.jsx component will just have the job of passing "About Us" into the menu item to make that corresponding component
2. React Router is an *essential* React library that simplifies the process of linking pages together. For normal websites, you would just have an <a> tag that has an "href" pointing to another HTML page. For React, React controls the "DOM" and makes that aforementioned process a bit trickier. To get around that trickiness, React Router is used to make things like Routers, Routes, Links, and so on. If you read the [tutorial for React Router](https://reacttraining.com/react-router/web/guides/quick-start), it gives you a better idea of what that implementation looks like.

For now, don't stress the React Router part because I will probably handle that.
