### ISSUE TITLE
As a user, I would like to view a page containing more info about SLP

### ISSUE THREAD

**Issue by bsalgado98** [StevensSEC/sec.club#8]
Similar to feature #7

Create a SLPInfo.jsx component that contains detailed info about SEC's Semester Long Project. Try to add pictures, walls of text, links to GitHub repos, and anything else you deem important. Key phrase here is "visually appealing" too so don't be afraid to get artsy.

**Comment by carpenterd777** [comment]
Should we close this issue? I feel like PR #71 would have close it.

**Comment by dyc3** [comment]
Yup, it should have
